version: "3.9"

services:
  web:
    build: .
    volumes:
      - type: bind
        source: .
        target: /var/www/kickstart-app

      # Uncomment the following lines to enable XDebug's remote debugging
      #
      #- type: bind
      #  source: ./docker/php/conf.d/xdebug.ini
      #  target: /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      #- type: bind
      #  source: ./docker/php/conf.d/error_reporting.ini
      #  target: /usr/local/etc/php/conf.d/error_reporting.ini
    ports:
      - "8008:80"
    depends_on:
      - db
    networks:
      - kickstart-net

  db:
    image: mariadb:10.10-jammy
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: yesplease
      MARIADB_USER: dbuser
      MARIADB_PASSWORD: dbpass
      MARIADB_DATABASE: dbname
    ports:
      - "6033:3306"
    networks:
      - kickstart-net

networks:
  kickstart-net: {}
