name: PHP Composer

on:
  push:
    branches: [ master, 3.1.x, 3.2.x, 4.0.x ]
  pull_request:
    branches: [ master, 3.1.x, 3.2.x, 4.0.x ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@2.16.0
      with:
        php-version: '8.1'
        tools: composer-require-checker

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Check for implicit requirements
      run: composer-require-checker

    - name: Run Psalm
      run: composer run-script psalm-ci ./src

    - name: Run Coding Style Check
      run: vendor/bin/phpcs ./src

    - name: Check dependencies for security advisories
      run: composer update --dry-run roave/security-advisories
